apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zen4jj8qr-nodejs 
  janus-idp.io/tekton: zen4jj8qr-nodejs
  backstage.io/kubernetes-id: zen4jj8qr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zen4jj8qr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml